plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.hekkelman.keylocker'
    compileSdk 36

    defaultConfig {
        applicationId "com.hekkelman.keylocker"
        minSdk 28
        targetSdk 36
        versionCode 9
        versionName '2.0.3'
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
            testCoverageEnabled = true

            tasks.withType(JavaCompile) {
                options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
            }
        }
    }

    lintOptions {
        abortOnError false
    }

//    flavorDimensions 'market'
//    productFlavors {
////        fdroid {
////            dimension = 'market'
////        }
////        play {
////            dimension = 'market'
////            versionNameSuffix = "-play"
////        }
//    }

    compileOptions {
        // Flag to enable support for the new language APIs
//        coreLibraryDesugaringEnabled true

        targetCompatibility JavaVersion.VERSION_11
        sourceCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/NOTICE.md'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.lifecycle:lifecycle-common-java8:2.9.2'
    implementation 'androidx.lifecycle:lifecycle-process:2.9.2'

    implementation('org.simpleframework:simple-xml:2.7.1') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.core:core-ktx:1.17.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    implementation "androidx.cardview:cardview:1.0.0"
    implementation 'androidx.recyclerview:recyclerview:1.4.0'

    // For control over item selection of both touch and mouse driven selection

    implementation 'com.google.android.material:material:1.12.0'

    // Include the sdk as a dependency
    implementation 'com.google.code.gson:gson:2.13.1'
    implementation 'androidx.drawerlayout:drawerlayout:1.2.0'
    implementation libs.activity

    def fragment_version = "1.8.9"

    implementation "androidx.fragment:fragment:$fragment_version"
    debugImplementation "androidx.fragment:fragment-testing:$fragment_version"

    implementation 'androidx.preference:preference:1.2.1'

    // sardine, for webdav
    implementation 'com.github.lookfirst:sardine:5.13'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
