plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.hekkelman.keylocker'
    compileSdkVersion 36

    defaultConfig {
        applicationId "com.hekkelman.keylocker"
        minSdk 28
        targetSdk 36
        versionCode 11
        versionName '2.0.4'
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            applicationIdSuffix = ".dev"
            versionNameSuffix = "-dev"
            testCoverageEnabled = true

            tasks.withType(JavaCompile) {
                options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
            }
        }
    }

    lintOptions {
        abortOnError false
    }

    flavorDimensions 'market'
    productFlavors {
        fdroid {
            dimension = 'market'
        }
//        play {
//            dimension = 'market'
//            versionNameSuffix = "-play"
//        }
    }

    compileOptions {
        // Flag to enable support for the new language APIs
//        coreLibraryDesugaringEnabled true

        targetCompatibility JavaVersion.VERSION_11
        sourceCompatibility JavaVersion.VERSION_11
    }

    buildFeatures {
        viewBinding true
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE.md'
        exclude 'META-INF/NOTICE.md'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation libs.lifecycle.common.java8
    implementation libs.lifecycle.process

    implementation(libs.simple.xml) {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
    implementation libs.appcompat
    implementation libs.core.ktx
    implementation libs.constraintlayout

    implementation libs.cardview
    implementation libs.recyclerview

    // For control over item selection of both touch and mouse driven selection

    implementation libs.material

    // Include the sdk as a dependency
    implementation libs.gson
    implementation libs.drawerlayout
    implementation libs.activity

    implementation libs.fragment
    implementation libs.biometric
    debugImplementation libs.fragment.testing

    implementation libs.preference

    // sardine, for webdav
    implementation libs.sardine

    coreLibraryDesugaring libs.desugar.jdk.libs
}
